= Polkadot Network Crawler

Crawler to gather the network information of the Polkadot nodes. The crawler connects to each available node, gets the
details about the node (software version, etc) and its peers to continue scan.

NOTE: The project is in an _early stage_ of development

.Features roadmap
- [ ] parse node details and extract info about software
- [x] save found nodes to a local file in JSON format

== Run Instructions

By default it saves details about found nodes into a file in `./log` directory, and logs progress, as amount of
fully processed peers to the console.

=== Using Docker

----
docker run -v $(pwd)/results:/results emeraldpay/polkadot-crawler
----

=== Using Gradle

Gradle could be installed from the website https://gradle.org/, or through SDKMAN https://sdkman.io/

.Run (and build) with command:
----
gradle run
----

=== Command Line Arguments

NOTE: If you run with Gradle you can pass arguments with `--args`. Ex. `--args="--export.file.targetdir=my_results_dir"`

- `--export.file.targetdir=<...>` - directory to save results, `./log` by default

== Build Instructions

Requirements:

- Java 11+
- Gradle 5.6+

.Local build
----
gradle build
----

.To build local Docker image:
----
gradle jibDockerBuild
----

== License

The core project code is released under Apache 2.0 license.

File `src/proto/dht.proto`, with the definition of DHT Protobuf messages, is taken from libp2p specification and has
the same license as it specified for the specification.