{
 "title": "Moonbeam Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(moonbeam_connect_ok_total)" }
   ]
  },
  {
   "title": "Active Peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(moonbeam_connect_ok_total) - sum(moonbeam_connect_ok_total offset 30m)"
    }
   ]
  },
  {
   "title": "New Peers (total/min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "moonbeam_connect_ok_total - (moonbeam_connect_ok_total offset 1m)"
    }
   ]
  },
  {
   "title": "Connections (total/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(moonbeam_connect_total[1m])"
    }
   ]
  },
  {
   "title": "Throughput (byte/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(moonbeam_transfer_bytes_total[1m])"
    }
   ]
  }
 ]
}